CREATE TABLE persona (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL CHECK (length(trim(nombre)) > 0),
    apellido VARCHAR(60) NOT NULL CHECK (length(trim(apellido)) > 0),
    dni VARCHAR(8) NOT NULL CONSTRAINT uk_persona_dni UNIQUE CHECK (dni ~ '^[0-9]{8}$'),
    email VARCHAR(120),
    telefono VARCHAR(9) CHECK (telefono IS NULL OR telefono = '' OR telefono ~ '^[0-9]{9}$')
);
